spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #配置返回Json的是null字段不显示
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.60.128
    port: 6379

server:
  context-path: /sell
wechat:
  #用借用账号里的mpAppId
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 1ff31525a1a19140562a289ff79c8b58
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: D:/Program Files/weixin_cert/h5.p12
  notifyUrl: http://yaostore.natapp1.cc/sell/pay/notify
  templateId:
    #可以配多个模板id
    orderStatus: ????????xxxxxxxx
    orderStatus1:
projectUrl:
  wechatMpAuthorize: http://yaostore.natapp1.cc
  wechatOpenAuthorize: http://yaostore.natapp1.cc
  sell: http://yaostore.natapp1.cc

